#!/bin/bash
set -e
cargo build --release
cp target/release/media-uploader media-upload/usr/local/bin/
dpkg-deb --build media-upload/
VER=$(cat Cargo.toml | grep version | sed -n -E 's/.*= "([0-9].[0-9].[0-9])"$/\1/p')
mv media-upload.deb media-upload-${VER}_amd64.deb